### PR TITLE
Add validator for board name

### PR DESCRIPTION
**Pull request by sztang**
Addressing #62 ; customized RegexValidator to check for special characters, allowing for commas, full-stops, question marks, parentheses, hyphens and forward slashes.

### CODE REVIEW

**Comment by twschiller** [comment]
Sorry for the delay, @sztang got tied up with work. Could you add some test cases of what would be permitted/not-permitted based on the rule? In particular, I think we need to allow some characters, e.g., ñ, to allow for board titles in non-english languages

**Comment by sztang** [comment]
No worries @twschiller . That makes sense, so I've changed the regex such that instead of accepting non-special characters, it'll reject specific characters (so things like ñ are allowed). Ran it on local server and it works, and I've included the list of excluded characters in a comment. Not too sure what you're referring to wrt test cases?

**Comment by twschiller** [comment]
Thanks! For test cases, one way to test it would be to make sure you can create a board with each.

Here's a rough sketch using pytest's parametrize feature: https://docs.pytest.org/en/stable/parametrize.html

```python
@pytest.mark.parametrize("test_input", [("here is a valid board name",), ("here is another valid board name",)])
def test_valid_board_names():
    # create a board with the name
    instance.clean()
```

You can then also have a test for invalid board names, where you use assert that an exception is raised: https://docs.pytest.org/en/stable/assert.html#the-writing-and-reporting-of-assertions-in-tests

**Comment by sztang** [comment]
Unfamiliar with pytest and how to use it in Django so I went with the standard unit test instead; ran this specific test locally and passed. I put it in test_models instead of test_board, since the validation is done on the model level and not the form level (I believe). Sorry for the delay, hope this is similar to what you had in mind!

**Comment by twschiller** [comment]
Thanks! Merged it in. We have a pytest plugin that can run standard Django tests using pytest. For those, the main difference is just that you can also use "assert" statements directly rather than the instance methods `self.assert<x>`. But what you have is good

**Pull request merged**
