### PR TITLE
Added Browser compatibility checks

### PR DESCRIPTION
**Pull request by HimanshuJanbandhu**

### CODE REVIEW

**Comment by HimanshuJanbandhu** [comment]
How can I increase the code coverage.

**Comment by twschiller** [comment]
@HimanshuJanbandhu I think you might have accidentally committed the dependency or distribution directories (e.g., the `bin`). You need to remove them from the commit. To avoid committing this directories in the future, you can add them to the `.gitignore`

**Comment by no-identd** [comment]
@HimanshuJanbandhu do you still work on this?

**Comment by HimanshuJanbandhu** [comment]
No

**Pull request closed without merging**
