### PR TITLE
L10n

### PR DESCRIPTION
**Pull request by mastizada**
fix issue #131 

All tests passed

### CODE REVIEW

**Comment by mastizada** [comment]
example

**Comment by twschiller** [comment]
Very cool, I'll take a detailed look later today. One minor thing I noticed is that that `<html lang="en-US">` in the base template needs to be varied based on the language

**Comment by mastizada** [comment]
@twschiller yes, forgot that. Also there is need to be language switcher button. Where I should add it? Profile page, Navigation bar, footer or something else? It is default Django select box.

**Comment by twschiller** [comment]
Overall, it looks good. I made a few minor tweaks that are currently sitting on the mastizada-l10n branch. I'm going to merge that branch in to master. Here's a list of changes.

- Re-order the LocaleMiddleware according to the Django docs
- Switch `en` language to `en-us`
- Include the language in html and opengraph tags
- Move the flakes8 config to tox.ini
- Make use of single/double quotes consistent in some places where they were inconsistent (they were inconsistent before your PR)

I'm not sure the best place to put the language selector. It should probably go on the in the header or footer, so that people who are not logged in can use it. Given that we currently don't have a consistent footer across the site, please add it to the header

Additionally, it would be good to allow the user to set their language preference in their settings on their profile. In both cases, I think you'll need to set a cookie one the user selects their language

**Pull request merged**
