### PR TITLE
Language selector

### PR DESCRIPTION
**Pull request by mastizada**
fix issue #140

### CODE REVIEW

**Comment by mastizada** [comment]
There is en-gb for British English, but US version is just en. I was wondered why changing language not works :D

**Comment by twschiller** [comment]
Thanks! I'll take a more detailed look tomorrow. Some things from a quick glance:

- I'll probably add a conditional to hide the the select widget if the instance only has one language configured. Does that seem reasonable?
- I'm not sure bootstrap-select is rendering properly on narrow screens when in select mode. You can see the options, but it doesn't look like there's a white div behind them
- bootstrap-select uses inline styles which violates the conservative style CSP we have. Looks like they've fixed the issue, but I'm not sure it's been released yet: https://github.com/silviomoreto/bootstrap-select/issues/1509. Based on their changes, it looks like it doesn't actually impact the rendering? If it doesn't matter, I'm probably just inclined to leave the CSP violation for now until the new release comes out.

**Comment by mastizada** [comment]
@twschiller I know only select2 and yesterday learned about bootstrap-select. Do you know what else we can use? Usual select looks very weird in header.

**Comment by twschiller** [comment]
Thanks for the commit. Did you try bootstrap's normal `form-control` class? It didn't look to bad to me. I don't have a problem using bootstrap-select, however later today I do want to dig into whether or not it's rendering properly on narrow screens (e.g., phones).

**Comment by mastizada** [comment]
using form-control:
form-control-switcher

Should I switch to that?

**Comment by twschiller** [comment]
Hmm, I don't think that's rendering properly, the arrow on the right should look more like this: https://getbootstrap.com/css/#selects

**Comment by mastizada** [comment]
It depends on operating system and browser. For me https://getbootstrap.com/css/#selects also looks like that.

**Comment by twschiller** [comment]
Learn something new everyday :). I think I'm going to merge your changes with the standard bootstrap selection widget for now. Another contributor is using the [selectize](https://selectize.github.io/selectize.js/) for implementing search (issue #125). Once that's committed, I'll switch over the language selection widget to also use selectize (with a bootstrap theme). Sound good?

**Comment by mastizada** [comment]
Yes, that one looks a lot better (selectize). I'm removing bootstrap-select from dependency, so we can leave form-control for now, later change all select widgets (for example in profile page) to selectize.

**Comment by twschiller** [comment]
Awesome, will merge later today

**Comment by twschiller** [comment]
Merged in the PR. Had to make a couple minor changes:
- Fix JS error when the selection form wasn't on the page
- Re-add the date-picker CSS file

**Pull request merged**
