### PR TITLE
fixes #125, added board search box

### LINKED ISSUE #125: Add a search box with autocomplete
Add a board search capability using an autocomplete widget. Might search by both board name and description

References:
- https://github.com/bassjobsen/Bootstrap-3-Typeahead ([on NPM](https://www.npmjs.com/package/bootstrap-3-typeahead)) 

Related Issues:
- Board Topics: #22

### PR DESCRIPTION
**Pull request by Prashant-Surya**
In full view:
------------------------
search-web

--------------------
In mobile view:
--------------------
search-mob

-----------------------
When an option is selected from drop-down it will redirect to the corresponding board page.

### CODE REVIEW

**Comment by Prashant-Surya** [comment]
@twschiller can u please check why integration is breaking?

**Comment by twschiller** [comment]
At first glance, I think the Travis CI build environment is just broken for external forks (the dummy DJANGO_SECRET_KEY variable isn't being used). I'll take a look at it and the PR tomorrow.

**Comment by twschiller** [comment]
For reference, it was breaking because the DJANGO_SECRET_KEY was set to hidden/secret in the Travis CI configuration. These variables aren't passed to the tests for merges because the merged code could steal/exfiltrate the secrets

**Comment by Prashant-Surya** [comment]
So how can this be fixed?

**Comment by twschiller** [comment]
I already fixed it, the DJANGO_SECRET_KEY can basically be set to anything during testing

**Comment by Prashant-Surya** [comment]
Okay. So that's why travis-ci build is passed?

**Comment by twschiller** [comment]
Yep! I'm going to start reviewing your changes in a little bit

**Comment by twschiller** [comment]
Thanks, I reviewed the PR and made some minor tweaks/changes.

A couple questions:
- Do we need to limit the number of results shown?
- Does search field need to be modified to also account for "board_desc" in the javascript? How is that attribute used?

Can you make the following modifications?:
- The JSON result should include the URL of the board (with slug) instead of the client having to assemble it from the ID. 
- Update selectize icon to indicate that it indicates the box is for search (or remove the icon entirely). Should be able to do by overriding the default CSS
- Add caching to the view

Here's a summary of changes I made in 96513fb4cf65dc5dfaab46b757f03c522fe5f049, you'll want to pull from the new branch:
- Add you to the list of contributors
- Add a couple test cases
- Switch from 'filter' to 'search' because search is how most people would refer to this feature 
- URL: Switched to 'api' from AJAX, since we'll eventually want to offer a full API. Also just used /api/boards/?query instead of /api/filter_boards/?query to match more closely with standard REST URL format
- Add DB indexes for title and description, otherwise search will be slow in the future
- Add translate block for search bar placeholder text
- filter_boards.js (now board_search.js): use double quotes, remove unused arguments
- add @require_safe decorator to the view
- Update copyright in project to be Open Synthesis Contributors (instead of just Todd)

**Comment by Prashant-Surya** [comment]
@twschiller should I make changes and update my existing pull request or create a new branch and send new pull request?

**Comment by twschiller** [comment]
Let's keep it within this PR. I'm not too familiar with how PRs work on GitHub, but I think you can merge my changes from 96513fb4cf65dc5dfaab46b757f03c522fe5f049 (just merge the branch) into your fork, make your changes, and then just re-push.

**Comment by Prashant-Surya** [comment]
I'm still searching for a way to remove the selectize icon. Please review the other changes and I'll update the commit with code for removing selectize icon when I found it.

**Comment by twschiller** [comment]
Thanks, I'll review the changes tomorrow. This StackOverflow question might help for figuring out how to remove the icon: https://stackoverflow.com/questions/30705505/how-to-change-the-caret-icon-in-selectize-js

**Comment by twschiller** [comment]
I made the CSS change to remove the carat and also fixed an issue with the form control changing sizes when the selectize JS is run. I also cleaned up the view code a little bit to make it more pythonic

**Comment by Prashant-Surya** [comment]
@twschiller thanks :) I'd like to work on more issues

**Comment by twschiller** [comment]
Take a look at the issues marked help wanted. I'd be happy to discuss any of them with you.

**Pull request merged**
